# Generated by Django 5.0.2 on 2024-06-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0002_property_google_maps_alter_property_imagen1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='google_maps',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
