# Generated by Django 5.0.2 on 2024-06-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0003_alter_property_google_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to='everapp'),
        ),
        migrations.AlterField(
            model_name='property',
            name='google_maps',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
