# Generated by Django 5.0.2 on 2024-06-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0004_property_imagen6_alter_property_google_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='imagen7',
            field=models.ImageField(blank=True, null=True, upload_to='everapp'),
        ),
        migrations.AddField(
            model_name='property',
            name='imagen8',
            field=models.ImageField(blank=True, null=True, upload_to='everapp'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
