# Generated by Django 5.0.2 on 2024-06-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0005_property_imagen7_property_imagen8_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_time', models.DateTimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
