# Generated by Django 5.0.2 on 2024-06-19 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0006_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_time',
            new_name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='purpose',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
