# Generated by Django 5.0.2 on 2024-06-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0008_recommendation_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='everapp'),
        ),
    ]
