# Generated by Django 5.0.2 on 2024-06-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0009_recommendation_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='mls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
