# Generated by Django 5.0.2 on 2024-06-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0011_rename_property_description_property_water_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='imagen9',
            field=models.ImageField(blank=True, null=True, upload_to='everapp'),
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='everapp'),
        ),
    ]
