# Generated by Django 5.0.2 on 2024-06-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0012_property_imagen9_property_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='imagen9',
        ),
    ]
