# Generated by Django 5.0.2 on 2024-06-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0014_best_places_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='best_places_recommendation',
            old_name='adress',
            new_name='address',
        ),
    ]
