# Generated by Django 5.0.2 on 2024-06-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0015_rename_adress_best_places_recommendation_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar_Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('place_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('thematic', models.CharField(blank=True, max_length=200, null=True)),
                ('range_of_price', models.CharField(blank=True, max_length=100, null=True)),
                ('title_h1', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('title_h4', models.CharField(blank=True, max_length=200, null=True)),
                ('description2', models.TextField(blank=True, max_length=600, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='everapp')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='everapp')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='everapp')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='everapp')),
            ],
            options={
                'verbose_name': 'recommend bar',
                'verbose_name_plural': 'recommend bars',
            },
        ),
        migrations.CreateModel(
            name='Restaurant_Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('place_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('thematic', models.CharField(blank=True, max_length=200, null=True)),
                ('range_of_price', models.CharField(blank=True, max_length=100, null=True)),
                ('title_h1', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('title_h4', models.CharField(blank=True, max_length=200, null=True)),
                ('description2', models.TextField(blank=True, max_length=600, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='everapp')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='everapp')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='everapp')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='everapp')),
            ],
            options={
                'verbose_name': ' Recommend Restaurant ',
                'verbose_name_plural': 'Recommend Restaurants',
            },
        ),
        migrations.DeleteModel(
            name='Best_places_Recommendation',
        ),
    ]
