# Generated by Django 5.0.2 on 2024-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0016_bar_recommendation_restaurant_recommendation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar_recommendation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bar_recommendation',
            name='title_h4',
        ),
        migrations.AlterField(
            model_name='bar_recommendation',
            name='description',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='bar_recommendation',
            name='description2',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_recommendation',
            name='description',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_recommendation',
            name='description2',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
