# Generated by Django 5.0.2 on 2024-06-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0017_remove_bar_recommendation_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_recommendation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='restaurant_recommendation',
            name='title_h4',
        ),
    ]
