# Generated by Django 5.0.2 on 2024-06-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0018_remove_restaurant_recommendation_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tour_Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_tour', models.CharField(blank=True, max_length=200, null=True)),
                ('tour_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tour_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=6000, null=True)),
                ('company_address', models.CharField(blank=True, max_length=200, null=True)),
                ('meet_up_at', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='everapp')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='everapp')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='everapp')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='everapp')),
            ],
            options={
                'verbose_name': 'recommend bar',
                'verbose_name_plural': 'recommend bars',
            },
        ),
        migrations.RemoveField(
            model_name='bar_recommendation',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='restaurant_recommendation',
            name='description2',
        ),
    ]
