# Generated by Django 5.0.2 on 2024-06-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0019_tour_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour_recommendation',
            options={'verbose_name': 'recommend tour', 'verbose_name_plural': 'recommend tours'},
        ),
    ]
