# Generated by Django 5.0.2 on 2024-06-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0021_galleryrecommendation_alter_recommendation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryrecommendation',
            old_name='open_hours',
            new_name='days_closed',
        ),
    ]
