# Generated by Django 5.0.2 on 2024-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0022_rename_open_hours_galleryrecommendation_days_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryrecommendation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
