# Generated by Django 5.0.2 on 2024-06-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0023_galleryrecommendation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_recommendation',
            name='place_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_recommendation',
            name='place_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
