# Generated by Django 5.0.2 on 2024-06-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0024_alter_bar_recommendation_place_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
