# Generated by Django 5.0.2 on 2024-06-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0025_restaurantrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantRecommendation',
        ),
    ]
