# Generated by Django 5.0.2 on 2024-07-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0026_delete_restaurantrecommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant_recommendation',
            options={'verbose_name': 'Recommend Restaurant', 'verbose_name_plural': 'Recommend Restaurants'},
        ),
        migrations.AlterField(
            model_name='property',
            name='google_maps',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
