# Generated by Django 5.0.2 on 2024-07-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0027_alter_restaurant_recommendation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='mls_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='code',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mls',
        ),
        migrations.AlterField(
            model_name='property',
            name='google_maps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
