# Generated by Django 5.0.2 on 2024-07-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0028_rename_mls_status_property_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar_recommendation',
            name='google_maps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galleryrecommendation',
            name='google_maps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_recommendation',
            name='google_maps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tour_recommendation',
            name='google_maps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
